
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Deploying SAM application..."
        sam deploy \
          --template-file build/packaged.yaml \
          --stack-name MyAppStack \
          --capabilities CAPABILITY_IAM \
          --region $AWS_DEFAULT_REGION \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
          
  post_build:
    commands:
      - echo "Done!" > dummy.txt
