version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install aws-sam-cli --upgrade

  pre_build:
    commands:
      - echo "Validating SAM template..."
      - sam validate --template template.yaml

  build:
    commands:
      - echo "Building SAM app..."
      - sam build --template template.yaml --build-dir build  # Todo en una línea

  post_build:
  commands:
    - echo "Empaquetando aplicación..."
    - sam package \
        --template-file build/template.yaml \
        --output-template-file build/packaged.yaml \
        --s3-bucket "$CODEPIPELINE_S3_BUCKET" \
        --region "$AWS_DEFAULT_REGION"
    
    # Verifica que el packaged.yaml tenga ubicaciones S3 válidas
    - echo "Contenido de packaged.yaml:"
    - cat build/packaged.yaml | grep CodeUri
artifacts:
  files:
    - build/packaged.yaml
    - build/params.json