version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Instalando SAM CLI..."
      - pip install --upgrade aws-sam-cli

  pre_build:
    commands:
      - echo "Validando template SAM..."
      - sam validate --template template.yaml

  build:
    commands:
      - echo "Construyendo la aplicación SAM..."
      - sam build --template template.yaml --build-dir build

  post_build:
    commands:
      - echo "Empaquetando SAM para despliegue..."
      - sam package \
          --template-file build/template.yaml \
          --output-template-file build/packaged.yaml \
          --s3-bucket "$CODEPIPELINE_S3_BUCKET" \
          --region "$AWS_DEFAULT_REGION" \
          --s3-prefix "${PROJECT_ID}/${APPLICATION_ID}/${STAGE}/SAMArtifacts" \
          --kms-key-id "$KMS_KEY_ID"
      - echo "Desplegando aplicación SAM..."
      - sam deploy \
          --template-file build/packaged.yaml \
          --stack-name "${APPLICATION_ID}-${STAGE}" \
          --capabilities CAPABILITY_IAM \
          --region "$AWS_DEFAULT_REGION" \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
      - echo "Despliegue completado."

artifacts:
  files:
    - build/packaged.yaml
