version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install aws-sam-cli --upgrade

  pre_build:
    commands:
      - echo "Validating SAM app template ..."
      - sam validate --template template.yaml

  build:
    commands:
      - echo "Building SAM app ..."
      - sam build --template template.yaml --build-dir build

  post_build:
    commands:
      - echo "Packaging SAM app ..."
      - sam package \
          --template-file build/template.yaml \
          --output-template-file build/packaged.yaml \
          --s3-bucket "${CODEPIPELINE_S3_BUCKET:-default-bucket}" \
          --region "${AWS_DEFAULT_REGION:-us-east-1}" \
          --s3-prefix "${PROJECT_ID}/${APPLICATION_ID}/${STAGE}/SAMArtifacts" \
          --kms-key-id "${KMS_KEY_ID:-default-key}"

      - echo "Deploying SAM app to stage: ${STAGE} ..."
      - sam deploy \
          --template-file build/packaged.yaml \
          --stack-name "${APPLICATION_ID}-${STAGE}" \
          --capabilities CAPABILITY_IAM \
          --region "${AWS_DEFAULT_REGION:-us-east-1}" \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset

artifacts:
  files:
    - build/packaged.yaml
    - build/params.json
