version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install aws-sam-cli --upgrade
  pre_build:
    commands:
      - echo "Validating SAM app template ..."
      - |
        sam validate --template template.yaml
  build:
    commands:
      - echo "Building SAM app ..."
      - |
        sam build \
        --template template.yaml --build-dir build
  post_build:
    commands:
      - echo "Packaging SAM app ..."
      - |
        - sam package \
        --template-file build/template.yaml \
        --output-template-file build/packaged.yaml \
        --s3-bucket $CODEPIPELINE_S3_BUCKET \
        --region $AWS_DEFAULT_REGION \
        --s3-prefix "${PROJECT_ID}/${APPLICATION_ID}/${STAGE}/SAMArtifac" \
        --kms-key-id "${KMS_KEY_ID}"

      - echo "Generating params.json ..."
      - echo "$STACK_PARAMETERS" > "${BUILD_OUTPUT_DIRECTORY}/params.json"

artifacts:
  files:
    - "${BUILD_OUTPUT_DIRECTORY}/packaged.yaml"
    - "${BUILD_OUTPUT_DIRECTORY}/params.json"
  discard-paths: false
