version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo "Verificando variables de entorno..."
      - echo "S3 Bucket: ${CODE_PIPELINE_S3_BUCKET}"
      - echo "Contenido del directorio:"
      - ls -la
      - sam validate --template-file template.yaml

  build:
    commands:
      - echo "Construyendo aplicación SAM..."
      - sam build --template-file template.yaml --build-dir build
      - echo "Verificando build:"
      - ls -la build/

  post_build:
    commands:
      - echo "Empaquetando aplicación..."
      - sam package \
          --template-file build/template.yaml \
          --output-template-file packaged.yaml \
          --s3-bucket ${CODE_PIPELINE_S3_BUCKET} \
          --region us-east-1
      - echo "Verificando artefacto generado:"
      - ls -la packaged.yaml

artifacts:
  files:
    - packaged.yaml
  discard-paths: no
