version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "install dependency ..."
  build:
    commands:
      - echo "package SAM app..."
      - sam build
      - sam package \
          --s3-bucket YOUR_S3_BUCKET_NAME \
          --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "create artifact para CodeDeploy..."
      - |
        cat > appspec.yml <<EOF
        version: 0.0
        Resources:
          - myLambdaFunction:
              Type: AWS::Lambda::Function
              Properties:
                Name: YOUR_LAMBDA_FUNCTION_NAME
        EOF
artifacts:
  files:
    - packaged.yaml
    - appspec.yml