version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install aws-sam-cli --upgrade

  pre_build:
    commands:
      - echo "Validating SAM template..."
      - sam validate --template template.yaml

  build:
    commands:
      - echo "Building SAM app..."
      - sam build --template template.yaml --build-dir build  # Todo en una línea

  post_build:
    commands:
      - echo "Packaging SAM app..."
      - sam package --template-file build/template.yaml --output-template-file build/packaged.yaml --s3-bucket "$CODEPIPELINE_S3_BUCKET" --region "$AWS_DEFAULT_REGION" --s3-prefix "${PROJECT_ID}/${APPLICATION_ID}/${STAGE}/SAMArtifacts" --kms-key-id "$KMS_KEY_ID"
      - echo "Deploying to ${STAGE}..."
      - sam deploy --template-file build/packaged.yaml --stack-name "${APPLICATION_ID}-${STAGE}" --capabilities CAPABILITY_IAM --region "$AWS_DEFAULT_REGION" --no-confirm-changeset --no-fail-on-empty-changeset

artifacts:
  files:
    - build/packaged.yaml
    - build/params.json