version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Validating SAM template..."
      - sam validate --template template.yaml
  build:
    commands:
      - echo "Building SAM application..."
      - sam build --template template.yaml --build-dir build
  post_build:
    commands:
      - echo "Packaging SAM application..."
      - sam package \
          --template-file build/template.yaml \
          --output-template-file build/packaged.yaml \
          --s3-bucket serverlessapi100 \
          --region us-east-1
artifacts:
  files:
    - build/packaged.yaml
